[package]
name = "citrus"
version = "0.1.0"
authors = ["Aurel Feer <aurel.feer@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23"
ash = {version = "0.37.1", default-features = false, features = ["linked", "debug"]}
ash-window = "0.12.0"
glam = "0.20.2"
glfw = {version = "0.49.1", features = ["vulkan"]}
raw-window-handle = "0.5.0"
noise = "0.7.0"
rusttype = "0.9.2"
