[package]
name = "citrus"
version = "0.1.0"
authors = ["Aurel Feer <aurel.feer@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23"
ash = {version = "0.35.1", default-features = false, features = ["linked", "debug"]}
ash-window = "0.9.0"
glam = "0.20.2"
glfw = {version = "0.43.0", features = ["vulkan"]}