[package]
name = "glfw"
version = "0.1.0"
authors = ["Aurel Feer <aurel.feer@gmail.com>"]
edition = "2018"

[dependencies]

noise = "0.5.1"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
