[package]
name = "citrus"
version = "0.1.0"
authors = ["Aurel Feer <aurel.feer@gmail.com>"]
edition = "2018"

[dependencies]
noise = "0.5.1"
gfx = "0.18.0"
gfx-backend-metal = "0.1.1"
winit = "0.18.1"

[build-dependencies]
shaderc = "0.3"
