[package]
name = "glfw"
version = "0.1.0"
authors = ["Aurel Feer <aurel.feer@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.10.0"
noise = "0.5.1"
vulkano = "0.11"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
